### ISSUE TITLE
config file not being read?

### ISSUE THREAD

**Issue by raleel** [austin-taylor/flare#2]
it appears the config file is not being read, even though I'm passing in a parameter for it at the command line.

`$ flare_beacon -c configs/elasticsearch.ini`
`[SUCCESS] Connected to elasticsearch on localhost:9200`

`$ grep port configs/elasticsearch.ini`
`es_port=9201`

shouldn't the first one connect on 9201?

**Comment by austin-taylor** [comment]
I identified the bug. The connection was being established to 9201, but the message was not being displayed properly. 

I have updated the code. Please pull down the new code and try again.

https://github.com/austin-taylor/flare/commit/68fa618085cda96f7339155cef68e8afea36b974

**Comment by austin-taylor** [comment]
Confirmed fix on local instance. Thank you for submitting the bug!
