### ISSUE TITLE
HTTPS support with auth and last Elasticsearch version support?

### ISSUE THREAD

**Issue by HawaYann** [austin-taylor/flare#36]
HI,

As I really wanted to make it works, I started to dig and find out that https support could be implemented relatively easily, as documented [here](https://elasticsearch-py.readthedocs.io/en/6.0.0/api.html#elasticsearch).

"SSL client authentication" and "RFC-1738 formatted URL" seam to work after I bypassed self.auth = None in the code.. this need to be adjust...

After adjusting the values in the config file to match Flow v9 from by Elasticsearch DB, in run_query(), the query:  resp = helpers.scan(query=query, client=self.es, scroll="90m", index=self.es_index, timeout="10m")
Return null... df is null
From:      df = pd.DataFrame([rec['_source'] for rec in resp])

And I am stuck here.. Not data retrieved.

[INFO] Attempting to connect to MY elasticsearch...
[SUCCESS] Connected to elasticsearch on IP:9200
[INFO] Gathering flow data... this may take a while...
{'query': {'bool': {'filter': [{'bool': {'must_not': [], 'must': [{'range': {'@timestamp': {'gte': 1565237742354, 'lte': 1565324142354, 'format': 'epoch_millis'}}}]}}, {'term': {'event_type': 'flow'}}], 'must': {'query_string': {'query': '*', 'analyze_wildcard': 'true'}}}}, '_source': ['src_addr', 'dst_addr', 'dst_port', '@timestamp', 'bytes', 'flowset_id']}
Empty DataFrame
Columns: []
Index: []
ERROR: Elasticsearch did not retrieve any data. Please ensure your settings are correct inside the config file.

On the server side I can see a GET with a 200, meaning auth is ok, but no data are pulled. It is followed by a DELETE, almost at the same time? weird.

I am wondering if you could make these change working? 
as I am not a coder but I feel that it is feasible. 

it is very frustrating, as a simple curl command like this work like a charm and retrieve the data, you will recognize the same request from Flare code:

curl --insecure -X GET -u user:password "https://IP:9200/logdb-*/_search?scroll=90m&timeout=10m&size=1000"

Thank you!

**Comment by SMAPPER** [comment]
The latest release now has use_ssl as an option in the configuration file and is successfully working in production systems.
