### ISSUE TITLE
Config option 'use_ssl' should be retreived as boolean

### ISSUE THREAD

**Issue by e-urban** [austin-taylor/flare#46]
I believe this config option below should be retrieved using getboolean() instead:
https://github.com/austin-taylor/flare/blob/1a064f5f9322d025f189c6b5fce82fdae72b5db7/flare/analytics/command_control.py#L81

When I set `use_ssl` in my config file like`use_ssl=False`, I then get the error:
```
ERROR: ConnectionError(HTTPSConnectionPool(host='hostname.local', port=9200): Max retries exceeded with url: /filebeat-*/_search?scroll=90m&size=1000&timeout=10m (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))) caused by: SSLError(HTTPSConnectionPool(host='hostname.local', port=9200): Max retries exceeded with url: /filebeat-*/_search?scroll=90m&size=1000&timeout=10m (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),)))
```

Flare is using the Elasticsearch constructor and this creates an `elasticsearch.Connection` (parent) from `elasticsearch.RequestsHttpConnection` (also would apply to default type of `elasticsearch.Urllib3HttpConnection` even though Flare doesn't use this that I could find).

If you look at [elasticsearch.connection.base.py#L49](https://github.com/elastic/elasticsearch-py/blob/3227e6d26b982cc6f466ace7791d80ae6a99b41c/elasticsearch/connection/base.py#L49) you can see that conditional would behave correctly with a boolean but would get set to True with any valid string (even 'False').

**Comment by e-urban** [comment]
I found a comment in another issue filed where a user seems to have run into this same problem with the ConnectionError I provided above.  They ended up hard coding use_ssl to false.  See https://github.com/austin-taylor/flare/issues/38#issuecomment-535073307.  

They did have multiple issues and the issue was eventually closed but as far as I can tell in the last comment even though they needed to update the elasticsearch package they still had to hardcode use_ssl.

**Comment by prashantmitm** [comment]
Hi, 

I am getting the same ssl error while running the flare_beacon command with loaded arguments.
I am no coder, could you please highlight what need to be changed and where?

Anything on the command_control.py? what exactly? Thanks

**Comment by e-urban** [comment]
> I am no coder, could you please highlight what need to be changed and where?
> 
> Anything on the command_control.py? what exactly? Thanks

Hi @prashantmitm, I opened a pull request with the change that resolved this for me.  See https://github.com/austin-taylor/flare/pull/49.

Just change line https://github.com/austin-taylor/flare/blob/1a064f5f9322d025f189c6b5fce82fdae72b5db7/flare/analytics/command_control.py#L81 to instead be ```self.use_ssl = self.config.config.getboolean('beacon', 'use_ssl')```.  Hope that helps.
