### ISSUE TITLE
Reason: No option 'filter' in section: 'beacon' Error

### ISSUE THREAD

**Issue by prashantmitm** [austin-taylor/flare#51]
Hi , i have recently installed Flare in my security Onion box, and I want to check the beacons against the flow data from my elastic search index. ES version = 5

I set the config.ini file as on the githun page, and matched it against Austin's medium blog too.

However I see the error that there is no Filter option in Beacon Section. I am sure Filter option is missing in my config file. Please advise what generic filter I could set there.

Thanks
Prashant

**Comment by crazydave85** [comment]
Hi,
If it helps, ive recently been going through setup and you can get away adding in filter=

as a value and will run ok. eg.

```
# Add custom filter below - Must be in Lucene syntax
# Example below
#filter=tags:internal_source AND tags:external_destination -dest_ip:8.8.8.8
filter=
#Elasticsearch fields for beaconing
field_source_ip=source.ip


```

at least it has worked for me so far :-)

**Comment by prashantmitm** [comment]
dest_ip as 8.8.8.8, should i replace it with my corporate DNS ip?
Or is it just acting as a value? and i just midlessly put it in the config file?

**Comment by crazydave85** [comment]
It's just a lucene example of what you can filter for as far as I can tell.

**Comment by SMAPPER** [comment]
Yes. This is correct. It's a lucene filter to further filter down your results based on tags or any other criteria. It's for improving performance.
